version: '3'
services:
  mongodb0:
    hostname: mongodb1
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_INITDB_ROOT_PASSWORD:admin
      - MONGO_INITDB_DATABASE:admin
    container_name: mongodb1
    restart: always
    ports:
      - 27017:27017